FROM node:16.14.0

ENV DEBIAN_FRONTEND=noninteractive

## Source Copy
WORKDIR /app
COPY . .

# Nodejs Package Installation
RUN rm -rf node_modules/
RUN npm install

# ## Server Start UP
CMD [ "npm", "run", "dev" ]